In [ ]:
In [ ]:
'''
Install 
!pip install numpy 
!conda install numpy --y
!pip3 install numpy
'''
In [5]:
import numpy as n
In [15]:
arr = n.array([1,2,58])
In [6]:
import numpy as np
arr = np.array([2,4,6])
In [8]:
print(type(arr))
'''
ndarray - 'N' dimentional Array
'''
<class 'numpy.ndarray'>
Out[8]:
"\nndarray - 'N' dimentional Array\n"
In [9]:
type(arr[0])
Out[9]:
numpy.int64
In [10]:
arr = np.array([1,2,3,"Inceptz"])
print(type(arr[0]))
<class 'numpy.str_'>
In [12]:
print(np.__version__)
1.18.2
In [16]:
arr.shape
Out[16]:
(3,)
In [18]:
arr_2d = np.array([[1,2,3],[5,6,7]])
In [20]:
print(arr_2d)
print(arr_2d.shape)
[[1 2 3]
 [5 6 7]]
(2, 3)
In [21]:
arr_2d[1:,:2]
Out[21]:
array([[5, 6]])
In [38]:
arr_3D = np.array([[[1,5,7],[4,8,9],[0,2,9],[6,7,8]]])
In [39]:
arr_3D
Out[39]:
array([[[1, 5, 7],
        [4, 8, 9],
        [0, 2, 9],
        [6, 7, 8]]])
In [40]:
arr_3D.shape
Out[40]:
(1, 4, 3)
Functions involved in creating an array
In [45]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
a = a.reshape((4,4))
In [46]:
a.shape
Out[46]:
(4, 4)
In [47]:
#linspace : This function generates elements which are equally spaced from each other
np.linspace(0,100,5)
Out[47]:
array([  0.,  25.,  50.,  75., 100.])
In [49]:
#arange : Generates values based on the step you specify 
np.arange(0,100,10)
Out[49]:
array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
In [50]:
#Zero - Fills the shape specified in the parameter with zeros
np.zeros((3,3))
Out[50]:
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])
In [52]:
np.zeros((4,2))
Out[52]:
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])
In [53]:
#ones - Fills the shape specified in the parameter with ones
np.ones((3,3))
Out[53]:
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])
In [55]:
#Identity matrix - with just the diagonal elements as ones
np.eye((3))
Out[55]:
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])
In [56]:
#Diagonal Matrix
np.diag([1,2,3,4,5])
Out[56]:
array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])
Operations with a numpy array
In [65]:
#Copy
arr = np.array([20,25,28])
dup = arr.copy()
arr[0] = 55

print(arr)
print(dup)
[55 25 28]
[20 25 28]
In [66]:
#View 
arr = np.array([50,46,57])
x = arr.view()
arr[0] = 60

print(arr)
print(x)
[60 46 57]
[60 46 57]
Iterating through arrays
For - for loops The 'n' dimentional arrays you have the n loops you need to access each seperate elements

In [67]:
arr
Out[67]:
array([60, 46, 57])
In [68]:
#1D Array 
for x in arr: 
    print(x)
60
46
57
In [70]:
#2D Array
for x in arr_2d:
    print(x)
[1 2 3]
[5 6 7]
In [71]:
for x in arr_2d:
    for y in x: 
        print(y)
1
2
3
5
6
7
In [74]:
arr_3D
Out[74]:
array([[[1, 5, 7],
        [4, 8, 9],
        [0, 2, 9],
        [6, 7, 8]]])
In [73]:
#3D Array
for i in arr_3D:
    print(i)
[[1 5 7]
 [4 8 9]
 [0 2 9]
 [6 7 8]]
In [75]:
for i in arr_3D:
    for j in i:
        print(j)
[1 5 7]
[4 8 9]
[0 2 9]
[6 7 8]
In [76]:
for i in arr_3D:
    for j in i:
        for x in j:
            print(x)
1
5
7
4
8
9
0
2
9
6
7
8
Addition, Subtraction and Multiplication in a numpy array
Broadcasting arrays
In [78]:
arr1 = np.array(range(1,17,1))
arr1 = arr1.reshape(4,4)
In [79]:
arr1
Out[79]:
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])
In [83]:
arr2 = np.array(range(10,170,10))
arr2 = arr2.reshape(4,4)
In [84]:
arr2
Out[84]:
array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])
In [85]:
a = np.array([1,2,3,4])
b = np.array([1,2])
In [86]:
a+b
'''
Adding matrices of unequal shapes 
'''
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-86-ca730b97bf8a> in <module>()
----> 1 a+b

ValueError: operands could not be broadcast together with shapes (4,) (2,) 
Addition
In [87]:
arr1+arr2
Out[87]:
array([[ 11,  22,  33,  44],
       [ 55,  66,  77,  88],
       [ 99, 110, 121, 132],
       [143, 154, 165, 176]])
In [88]:
print(np.add(arr1,arr2))
[[ 11  22  33  44]
 [ 55  66  77  88]
 [ 99 110 121 132]
 [143 154 165 176]]
Subtraction
In [89]:
arr1-arr2
Out[89]:
array([[  -9,  -18,  -27,  -36],
       [ -45,  -54,  -63,  -72],
       [ -81,  -90,  -99, -108],
       [-117, -126, -135, -144]])
In [90]:
print(np.subtract(arr1,arr2))
[[  -9  -18  -27  -36]
 [ -45  -54  -63  -72]
 [ -81  -90  -99 -108]
 [-117 -126 -135 -144]]
Multiply
In [97]:
arr1 = np.array(range(1,17,1))
arr1 = arr1.reshape(4,4)

arr2 = np.array(range(10,170,10))
arr2 = arr2.reshape(4,4)
In [98]:
arr1
Out[98]:
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])
In [99]:
arr2
Out[99]:
array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160]])
In [101]:
arr1*arr2
Out[101]:
array([[  10,   40,   90,  160],
       [ 250,  360,  490,  640],
       [ 810, 1000, 1210, 1440],
       [1690, 1960, 2250, 2560]])
In [100]:
np.multiply(arr1,arr2)
Out[100]:
array([[  10,   40,   90,  160],
       [ 250,  360,  490,  640],
       [ 810, 1000, 1210, 1440],
       [1690, 1960, 2250, 2560]])
division
In [102]:
np.divide(arr1,arr2)
Out[102]:
array([[0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1]])
In [104]:
arr1*100
Out[104]:
array([[ 100,  200,  300,  400],
       [ 500,  600,  700,  800],
       [ 900, 1000, 1100, 1200],
       [1300, 1400, 1500, 1600]])
Joining two numpy arrays
In [105]:
arr1 = np.array([1,2,3,5])
arr2 = np.array([5,6,7,8])
In [108]:
#The arrays are joined as rows
np.stack((arr1,arr2),axis = 0)
Out[108]:
array([[1, 2, 3, 5],
       [5, 6, 7, 8]])
In [107]:
#The arrays are joined as columns
np.stack((arr1,arr2),axis= 1)
Out[107]:
array([[1, 5],
       [2, 6],
       [3, 7],
       [5, 8]])
In [109]:
np.stack((arr1,arr2),axis= 2)
'''
AxisError is when you reference an axis which is not there
'''
---------------------------------------------------------------------------
AxisError                                 Traceback (most recent call last)
<ipython-input-109-3483c240baff> in <module>()
----> 1 np.stack((arr1,arr2),axis= 2)

<__array_function__ internals> in stack(*args, **kwargs)

~/anaconda3/envs/python3/lib/python3.6/site-packages/numpy/core/shape_base.py in stack(arrays, axis, out)
    427 
    428     result_ndim = arrays[0].ndim + 1
--> 429     axis = normalize_axis_index(axis, result_ndim)
    430 
    431     sl = (slice(None),) * axis + (_nx.newaxis,)

AxisError: axis 2 is out of bounds for array of dimension 2
In [110]:
#hstack - horizontal stack as a column
np.hstack((arr1,arr2))
Out[110]:
array([1, 2, 3, 5, 5, 6, 7, 8])
In [112]:
#Vstack - Vertical stack as a column
np.vstack((arr1,arr2))
Out[112]:
array([[1, 2, 3, 5],
       [5, 6, 7, 8]])
In [114]:
#concatenate
arr = np.concatenate((arr1,arr2))
print(type(arr))
<class 'numpy.ndarray'>
Matrix Multiplication
(m,n) (n,k) - no of columns in the first matrix should be equal to the number of rows in the second matrix the resultant matrix will be of shape (m,k)

In [123]:
arr1 = np.array(range(1,17,1))
arr1 = arr1.reshape(2,8)

print(arr1)

arr2 = np.array(range(10,170,10))
arr2 = arr2.reshape(8,2)
print(arr2)
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[ 10  20]
 [ 30  40]
 [ 50  60]
 [ 70  80]
 [ 90 100]
 [110 120]
 [130 140]
 [150 160]]
In [120]:
print(np.dot(arr1,arr2))
[[3720 4080]
 [8840 9840]]
Difference between just multiply and dot product
In [121]:
arr1 = np.array(range(1,17,1))
arr1 = arr1.reshape(4,4)

arr2 = np.array(range(10,170,10))
arr2 = arr2.reshape(4,4)

print(arr1)
print(arr2)

np.multiply(arr1,arr2)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]
Out[121]:
array([[  10,   40,   90,  160],
       [ 250,  360,  490,  640],
       [ 810, 1000, 1210, 1440],
       [1690, 1960, 2250, 2560]])
In [124]:
## Splitting 

arr = np.array([6,7,8,9,10,11])
np.array_split(arr,3)
Out[124]:
[array([6, 7]), array([8, 9]), array([10, 11])]
In [126]:
arr = np.array([6,7,8,9,10,11,50,44])
np.array_split(arr,3)
Out[126]:
[array([6, 7, 8]), array([ 9, 10, 11]), array([50, 44])]
In [128]:
## Sorting of numpy arrays
np.sort(arr)
Out[128]:
array([ 6,  7,  8,  9, 10, 11, 44, 50])
In [133]:
arr_2d = np.array([[1,2,3],[20,9,2]])
In [134]:
## 2D Sorting of numpy arrays - sorts for each arrays seperately
np.sort(arr_2d)
Out[134]:
array([[ 1,  2,  3],
       [ 2,  9, 20]])
In [136]:
# Search 
arr
np.where(arr >8)
Out[136]:
(array([3, 4, 5, 6, 7]),)
In [137]:
arr
Out[137]:
array([ 6,  7,  8,  9, 10, 11, 50, 44])
In [145]:
np.sort(arr)
Out[145]:
array([ 3,  5,  6,  7, 10, 20])
In [162]:
np.sort(arr)
Out[162]:
array([ 3,  5,  6,  7,  8, 10, 20])
In [147]:
np.sort(arr)
Out[147]:
array([ 3,  5,  6,  7,  8, 10, 20])
Statistics with Numpy
In [167]:
arr = np.array([1,5,6,7,8,9])
np.mean(arr)
Out[167]:
6.0
In [168]:
#median
np.median(arr)
Out[168]:
6.5
In [172]:
#median
arr_2d = np.array([[1,2,3],[5,6,7]])
print("arr_2d",arr_2d)
arr_2d.mean(axis = 0)
arr_2d [[1 2 3]
 [5 6 7]]
Out[172]:
array([3., 4., 5.])
In [173]:
#median
arr_2d = np.array([[1,2,3],[5,6,7]])
print("arr_2d",arr_2d)
arr_2d.mean(axis = 1)
arr_2d [[1 2 3]
 [5 6 7]]
Out[173]:
array([2., 6.])
In [174]:
#Mean of the whole matrix 
arr_2d.mean()
Out[174]:
4.0
In [175]:
#standard deviation
np.std(arr)
Out[175]:
2.581988897471611
In [176]:
#variance 
np.var(arr)
Out[176]:
6.666666666666667
In [177]:
#percentile 
scores = [80,90,70,85,60,55,75,89,12,13,15]
np.percentile(scores,80)
Out[177]:
85.0
In [179]:
#random
import matplotlib.pyplot as plt 
norm_data = np.random.normal(10,1.0,50000000)
plt.hist(norm_data,200)
plt.show()

In [181]:
np.random.randint(1,100)
Out[181]:
14
In [182]:
np.random.rand(1,100)
Out[182]:
array([[0.45982382, 0.95549395, 0.7416957 , 0.43541928, 0.42848454,
        0.41161377, 0.11976452, 0.66134618, 0.25872313, 0.14934954,
        0.21971127, 0.16070529, 0.69487184, 0.65440804, 0.67284127,
        0.79325041, 0.4275366 , 0.86354799, 0.94006677, 0.73232261,
        0.27112323, 0.50122027, 0.3261849 , 0.90471238, 0.68904225,
        0.77673409, 0.71506608, 0.01939747, 0.72427391, 0.70996292,
        0.7629395 , 0.9820574 , 0.20166017, 0.1127724 , 0.06996525,
        0.05128712, 0.62744471, 0.71828669, 0.97369891, 0.2721683 ,
        0.00127236, 0.21290453, 0.62599925, 0.77997182, 0.89293181,
        0.79864319, 0.38954702, 0.50066886, 0.23164432, 0.40025815,
        0.94962791, 0.96917824, 0.13269846, 0.16470601, 0.09748119,
        0.80521854, 0.19301869, 0.25317777, 0.40573477, 0.85205528,
        0.02551125, 0.81027714, 0.1238716 , 0.49020036, 0.68607818,
        0.22135774, 0.85520509, 0.74568177, 0.388829  , 0.7313211 ,
        0.69976191, 0.60689101, 0.23677059, 0.48347653, 0.49146047,
        0.39875061, 0.37247346, 0.52956434, 0.36842996, 0.89326486,
        0.53029978, 0.21169905, 0.40832484, 0.86371825, 0.1167828 ,
        0.38446906, 0.54297152, 0.26770668, 0.43998678, 0.62825092,
        0.65631528, 0.48978384, 0.39495241, 0.49060431, 0.9191752 ,
        0.75672561, 0.60495684, 0.94763827, 0.62239192, 0.57202647]])
In [183]:
np.random.randint(1,100,size = (2,2))
Out[183]:
array([[30, 46],
       [39, 57]])
In [184]:
np.random.randint(1,100,size = (2,4))
Out[184]:
array([[61, 27, 24, 38],
       [89, 85, 31, 80]])
In [189]:
np.random.choice([1,5,7,10],size = (1,2))
Out[189]:
array([[7, 1]])
In [194]:
import matplotlib.pyplot as plt 
import seaborn as sns

chi = np.random.chisquare(df = 1,size = 100000)
sns.distplot(chi,hist = False)
plt.show()
/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/scipy/stats/stats.py:1713: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  return np.add.reduce(sorted[indexer] * weights, axis=axis) / sumval
