Exercise 1: NumPy: Create an array with values ranging from 12 to 38
In [1]:

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]

In [6]:
import numpy as np
# print(np.arange(12,38,1)) or else as below
print(np.arange(12,38))

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


Exercise 2: Add a border around an existing array
Hint: np.pad()
In [2]:

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]

In [78]:
identity_mat = np.ones((3,3))
# borderd_res = np.pad(identity_mat,pad_width=1,mode="constant",constant_values=2)  or else
borderd_res = np.pad(identity_mat,1)  
print(borderd_res)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


Exercise 3: Convert a list and tuple into arrays
In [6]:

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]
Also try np.asarray for the problem above!

In [36]:
import numpy as np
list_data = [1,2,3,4,5,6,7,8]
print("list :",list_data)
list_asarray = np.asarray(list_data)
print("list as array :",list_asarray)

tuple_val = (1,2,3,4,5,6) 
print("tuple :", tuple_val)
tuple_asarray = np.asarray(tuple_val)
print("tupe as array :",tuple_asarray)

tuple_val = ([8,4,6],[1,2,3]) 
print("tuple :", tuple_val)
tuple_asarray = np.asarray(tuple_val)
print("tupe as array :")
print(tuple_asarray)

list : [1, 2, 3, 4, 5, 6, 7, 8]
list as array : [1 2 3 4 5 6 7 8]
tuple : (1, 2, 3, 4, 5, 6)
tupe as array : [1 2 3 4 5 6]
tuple : ([8, 4, 6], [1, 2, 3])
tupe as array :
[[8 4 6]
 [1 2 3]]


Exercise 4: Convert the values of Centigrade degrees into Fahrenheit degrees
In [4]:

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]

In [6]:
import numpy as np
fahrenheit_values = [0,12,45.21,34,99.91]
f_as_array = np.asarray(fahrenheit_values)
print("Values in Fahrenheit degrees: ",f_as_array)
print("Values in  Centigrade degrees:",(5*f_as_array/9 - 5*32/9))


Values in Fahrenheit degrees:  [ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees: [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Exercise 5: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements.
In [7]:

Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24

In [26]:
import numpy as np
array_val = np.array((11,2,3),dtype ='float')
print("array value : ",array_val)
print("Size of the array: ",np.size(array_val))
print("Length of one array element in bytes: ",array_val.itemsize)
print("Total bytes consumed by the elements of the array: ",array_val.nbytes)

array value :  [11.  2.  3.]
Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


Exercise 6: Get the unique elements of an array
In [9]:

Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]

In [36]:
my_list = [10,10,20,20,30,30]
import numpy as np
ary_val = np.array(my_list)
print("Original array: ",ary_val)
uniq_value = np.unique(ary_val)
print("Unique elements of the above array: ",uniq_value)
tuple_val = ([1,1],[2,3])
two_d_aray = np.asarray(tuple_val)
print("Original array:")
print(two_d_aray)
uniq_two_d_aray = np.unique(two_d_aray)
print("Unique elements of the above array: ",uniq_two_d_aray)

Original array:  [10 10 20 20 30 30]
Unique elements of the above array:  [10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:  [1 2 3]


Exercise 7: Change the dimension of an array
In [11]:

Original array: [1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3) -> 3 rows and 3 columns 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [42]:
import numpy as np
ary_data = np.array((1,2,3,4,5,6,7,8,9))
print("Original array: ",ary_data)
ary_shape = ary_data.reshape(3,3)
print(ary_shape)

Original array:  [1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Exercise 8: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive
In [12]:

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]

In [45]:
import numpy as np 
# np.arange(2.5,6.5,0.13793103)
np.linspace(2.5,6.5,30)

array([2.5       , 2.63793103, 2.77586207, 2.9137931 , 3.05172414,
       3.18965517, 3.32758621, 3.46551724, 3.60344828, 3.74137931,
       3.87931034, 4.01724138, 4.15517241, 4.29310345, 4.43103448,
       4.56896552, 4.70689655, 4.84482759, 4.98275862, 5.12068966,
       5.25862069, 5.39655172, 5.53448276, 5.67241379, 5.81034483,
       5.94827586, 6.0862069 , 6.22413793, 6.36206897, 6.5       ])

Exercise 9: Convert 1-D arrays as columns into a 2-D array
In [21]:

Array1: [10 20 30]
Array2: [40 50 60]
Converted array
[[10 40]
 [20 50]
 [30 60]]

In [52]:
import numpy as np 
first_array = np.array((10,20,30))
second_array = np.array((40,50,60))
print("Array1: ",first_array)
print("Array2: ",second_array)
print("Converted array : ")
print(np.column_stack((first_array,second_array)))

Array1:  [10 20 30]
Array2:  [40 50 60]
Converted array : 
[[10 40]
 [20 50]
 [30 60]]


Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4
In [22]:

Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]

In [75]:
import numpy as np
array1 = np.zeros((5,5))
print("Original array: ")
print(array1)
print("Row values ranging from 0 to 4. : ")
array1 += np.arange(5)
print(array1)

Original array: 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4. : 
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Exercise 11: Sum of all the multiples of 3 or 5 below 100
In [23]:

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318

In [13]:
import numpy as np
initial_aray = np.arange(1,100)
print("range of values :",initial_aray)
req_values = initial_aray[(initial_aray%3==0) | (initial_aray%5==0)]
print("All the multiples of 3 or 5 below 100 : ",req_values)
print("Sum of all the multiples of 3 or 5 below 100 : ",np.sum(req_values))

range of values : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
All the multiples of 3 or 5 below 100 :  [ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
Sum of all the multiples of 3 or 5 below 100 :  2318


Exercise 12: Combine a one and a two dimensional array together and display their elements
Hint : np.nditer()
In [28]:
x = np.arange(4)
y = np.arange(4)
for a, b in np.nditer([x,y]):
    print(a)
    print(b)
0
0
1
1
2
2
3
3
In [29]:

One dimensional array:
[0 1 2 3]
Two dimensional array:
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7

In [27]:
import numpy as np 
first_array = np.arange(4)
second_array = np.arange(8).reshape(2,4)

for x,y in np.nditer([first_array,second_array]):
    print(x,y)
print(first_array)

0 0
1 1
2 2
3 3
0 4
1 5
2 6
3 7
[0 1 2 3]


In [36]:
import numpy as np 
first_aray = np.arange(4)
second_aray = np.arange(8).reshape(2,4)
print("One dimensional array: : ",first_aray)
print("Two dimensional array: : \n",second_aray)
print("Iterator Array : ")
for x,y in np.nditer([first_aray,second_aray]):
    print("%d:%d" % (x,y))

One dimensional array: :  [0 1 2 3]
Two dimensional array: : 
 [[0 1 2 3]
 [4 5 6 7]]
Iterator Array : 
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


Exercise 13: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.
In [30]:

Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]

In [61]:
import numpy as np
listvalues  = [0.42436315, 0.48558583, 0.32924763 ,0.7439979  ,0.58220701, 0.38213418 ,0.5097581 ,0.34528799 ,0.1563123]
shaped_Aray = np.asarray(listvalues).reshape(3,3)
print("Original array: \n", shaped_Aray,"\n")
shaped_Aray[shaped_Aray>0.5] = 0.5
print("Values Greater Than 0.5 Replaced With o.5 : \n",shaped_Aray)

Original array: 
 [[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]] 

Values Greater Than 0.5 Replaced With o.5 : 
 [[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


Exercise 14: Add a new row to an empty numpy array
In [34]:

Empty array:
[]
After adding two new arrays:
[[10 20 30]
 [40 50 60]]

In [78]:
import numpy as np
a_array = np.empty((0,3),int)
print("Empty Array : \n",an_array)
b_array = [10,20,30]
c_Array = [40,50,60]
print(np.append(a_array,np.array([b_array,c_Array]),axis =0))

Empty Array : 
 []
[[10 20 30]
 [40 50 60]]


Exercise 15: Write a NumPy program to join a sequence of arrays along a new axis.
In [35]:

Original arrays:
[1 2 3]
[2 3 4]
Sequence of arrays along a new axis:
[[1 2 3]
 [2 3 4]]

Original arrays:
[[1]
 [2]
 [3]]

[[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]

In [102]:
import numpy as np
a1 = np.array(([1,2,3]))
a2 = np.array(([2,3,4]))
print("Original arrays: \n",a1,"\n",a2)
print("Sequence of arrays along a new axis: \n",np.vstack((a1,a2)),"\n")
a3 = np.array([[1],[2],[3]])
a4 = np.array([[2],[3],[4]])
print("Original arrays: \n",a3,"\n\n",a4)
print("Sequence of arrays along a new axis: \n",np.vstack((a3,a4)))

Original arrays: 
 [1 2 3] 
 [2 3 4]
Sequence of arrays along a new axis: 
 [[1 2 3]
 [2 3 4]] 

Original arrays: 
 [[1]
 [2]
 [3]] 

 [[2]
 [3]
 [4]]
Sequence of arrays along a new axis: 
 [[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
